image: python:3.8

stages:
  - install
  - test

cache:
  paths:
    - venv/

install_dependencies:
  stage: install
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  artifacts:
    paths:
      - venv/

test:
  stage: test
  script:
    - source venv/bin/activate
    - python -m unittest discover